leftnav:
- identifier: 5ec36222-5416-8355-69fe-53d15a823d4a
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: d07c8b8c-c87c-4495-59c5-650c2eb9905b
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 42e6d30b-9c4e-463c-b005-156d73734cf2
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 1953abf8-2f71-b9c5-a4c3-2ef0ac3f03b9
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 2bba04f5-2e93-21f4-3ad8-294bf4033e5c
  name: Exams
  pageRef: /pages/exams
  weight: 50
